import React from 'react'
import Leftnav from '@/components/Leftnav'
export const metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <>
            <div className=' p-[69px]'>
                <div className='grid grid-cols-5 mt-5'>
                    <Leftnav />
                    <div className='pl-5 col-start-2 col-end-6 '>
                        {children}
                    </div>
                </div>
            </div>

        </>
    );
}
