import React from 'react'

import Leftnav from '@/components/Leftnav'
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <>
            <div className='grid grid-cols-5 p-[69px]'>
                <Leftnav />
                <div className='pl-5 col-start-2 col-end-6'>
                    {children}
                </div>
            </div>

        </>
    );
}
